cook_css/cook_css/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("eat/", include("eat.urls")),
    path("signup/", include("signup.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cook_css/eat/urls.py
from django.contrib import admin
from django.urls import path
from signup.models import User
from .views import EatListView, EatDetailView, EatCreateView, EatUpdateView, EatDeleteView, EatTimeLineListView, EatUsersListView, EatFindListView, EatGoodUsersListView, good, EatQuoteDetailView, EatQuoteCreateView

app_name = "eat"

urlpatterns = [
    path('index/', EatListView.as_view(), name="index"),
    path('detail/<int:pk>/', EatDetailView.as_view(), name="detail"),
    path('create/', EatCreateView.as_view(), name="create"),
    path('update/<int:pk>/', EatUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', EatDeleteView.as_view(), name="delete"),
    path('timeline/', EatTimeLineListView.as_view(), name="timeline"),
    path('users/<int:users_id>/', EatUsersListView.as_view(), name="users"),
    path('find/', EatFindListView.as_view(), name="find"),
    path('<int:pk>/', good, name="good"),
    path('detail/quote/<int:pk>/', EatQuoteDetailView.as_view(), name="quote_detail"),
    path('create/quote/<int:pk>/', EatQuoteCreateView.as_view(), name="quote_create"),
    #path('<int:pk>', GoodUpdateView.as_view(), name = 'good')
    path('list/<int:users_id>/', EatGoodUsersListView.as_view(), name='good_users_list')

]
 

cook_css/eat/models.py
from django.db import models
from django.conf import settings



class Recipe(models.Model):
    recipe_name = models.CharField("レシピ名", max_length=20)
    site = models.CharField("参考サイト", max_length=2048, blank=True, null=False)
    memo = models.TextField("メモ", max_length=1000, blank=True, null=False)
    photo = models.ImageField("写真", upload_to="Media", blank=True, null=False)
    ingredient = models.CharField("材料", max_length=200)
    TYPE = (
        ("スープ", "スープ"),
        ("ご飯", "ご飯"),
        ("おかず", "おかず"),
        ("スイーツ", "スイーツ")
        )
    type = models.CharField("種類", max_length=20, choices=TYPE)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="create_user"
        )
    good_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        verbose_name="いいねしたユーザー",
        blank=True,
        related_name="good_user")
    PUBLIC = (
        ("公開", "公開"),
        ("非公開", "非公開"),
        ("友達のみ", "友達のみ")
        )
    public = models.CharField("公開", max_length=20, choices=PUBLIC, default="非公開")
    #このレシピを元に参考cookを作った人
    quote_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        verbose_name="参考cookユーザー",
        blank=True,
        related_name="quote_user"
        )
    #参考cookを作成したレシピ
    quote_recipe = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="quote_recipe_name",
        )
    #この投稿自体が参考cookかどうか
    quote = models.CharField(max_length=10, default="無し")


    def __str__(self):
        return self.recipe_name

    def summary(self):
        return self.site[:20]

cook_css/eat/forms.py
from django import forms
from .models import Recipe

class RecipeForm(forms.ModelForm):

    ingredient = forms.CharField(
        widget=forms.TextInput(attrs={"size":40}),
        max_length=200,
        label="材料"
        )

    class Meta:
        model = Recipe
        exclude = ["user", "good_coount", "good_user", "quote_user", "quote_recipe", "quote"]

cook_css/eat/views.py
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.utils.safestring import mark_safe

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.db.models import Q


from signup.models import User
from eat.models import Recipe
from eat.forms import RecipeForm
from itertools import chain



class OnlyUserRequiredMixin(UserPassesTestMixin):

    raise_exception = True

    def test_func(self):
        user = self.request.user
        obj = get_object_or_404(Recipe, id=self.kwargs['pk'])
        return user.pk == obj.user.id or user.is_superuser

#投稿編集の制限
def good(request, *args, **kwargs):
    if request.user.is_authenticated:
        #いいねする投稿の情報を取得
        recipe = Recipe.objects.get(id=kwargs['pk'])

        #投稿にすでにいいねしている場合
        if Recipe.objects.filter(id=recipe.id, good_user=request.user).exists():
            recipe.good_user.remove(request.user)
            recipe.save()
        else:
            recipe.good_user.add(request.user)
            recipe.save()
    #前回表示していたページにリダイレクト
        return redirect(request.META.get('HTTP_REFERER'))
    else:
        return redirect("signup:login")






#いいねのリスト
class EatGoodUsersListView(ListView):
    model = Recipe
    template_name = "eat/recipe_good_users_list.html"
    paginate_by = 20

    def get_queryset(self):
        search = self.request.GET.get("search")
        order = self.request.GET.get("order")
        users_id = self.kwargs.get('users_id')
        users = User.objects.get(id=users_id)

        object_list = Recipe.objects.filter(good_user=users_id)
        #ログイン中
        if self.request.user.is_authenticated:
            #フォローしているユーザーの友達のみ公開の投稿を絞り込む
            object_list = object_list.filter(
                Q(user__in=self.request.user.follow.all(), public="友達のみ")|
                Q(public="公開")
                )
        #ログアウト中
        else:
            object_list = object_list.exclude(
                Q(public="非公開")|
                Q(public="友達のみ")
                )

        if search:
            object_list = object_list.filter(
                Q(good_user=users_id),
                Q(recipe_name__contains=search)|
                Q(ingredient__contains=search)|
                Q(type__contains=search)
                )
            if order == "new":
                object_list = object_list.order_by("-date")
            elif order == "old":
                object_list = object_list.order_by("date")
            else:
                object_list = object_list.order_by("-date")
        elif order == "old":
            object_list = object_list.order_by("date")
        else:
            object_list = object_list.order_by("-date")
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users_id = self.kwargs.get('users_id')
        users = User.objects.get(id=users_id)
        recipe_count = Recipe.objects.filter(user=users).count()
        follower_count = User.objects.filter(follow__username=users).count()
        context["recipe_count"] = recipe_count
        context["users"] = users
        context["follower_count"] = follower_count
        return context

#マイページのレシピ一覧
class EatListView(LoginRequiredMixin, ListView):
    model = Recipe
    paginate_by = 20
    login_url = "/signup/login/"

    def get_queryset(self):
        search = self.request.GET.get("search")
        order = self.request.GET.get("order")

        if self.request.user.is_authenticated:
            filter_object = Recipe.objects.filter(user=self.request.user)
            if search:
                filter_object = Recipe.objects.filter(
                    Q(user=self.request.user),
                    Q(recipe_name__contains=search)|
                    Q(ingredient__contains=search)|
                    Q(type__contains=search)
                    )
                if order == "new":
                    object_list = filter_object.order_by("-date")
                elif order == "old":
                    object_list = filter_object
                else:
                    object_list = filter_object.order_by("-date")
            elif order == "old":
                object_list = filter_object
            else:
                object_list = filter_object.order_by("-date")
            return object_list

    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            context = super().get_context_data(**kwargs)
            users = User.objects.get(id=self.request.user.id)
            recipe_count = Recipe.objects.filter(user=users).count()
            follower_count = User.objects.filter(follow__username=users).count()
            context["recipe_count"] = recipe_count
            context["users"] = users
            context["follower_count"] = follower_count
            return context

#選択消去
    def post(self, request, **kwargs):
        deletes = request.GET.get("deletes")

        if deletes == "deletes":
            users_id = self.kwargs.get('users_id')
            recipe_pks = request.POST.getlist('delete')
            Recipe.objects.filter(pk__in=recipe_pks).delete()
            return redirect('eat:index')




class EatTimeLineListView(LoginRequiredMixin, ListView):
    model = Recipe
    paginate_by = 5
    login_url = "/signup/login/"
    template_name = "eat/recipe_timeline_list.html"

    def get_queryset(self):
        search = self.request.GET.get("search")
        order = self.request.GET.get("order")

        if self.request.user.is_authenticated:
            filter_object = Recipe.objects.filter(
                Q(user__in=self.request.user.follow.all())|
                Q(user=self.request.user)
                )
            #非公開の投稿は表示しない
            filter_object = filter_object.exclude(public="非公開")
            #検索ワードがある場合
            if search:
                filter_object = filter_object.filter(
                    Q(user__username__contains=search)|
                    Q(recipe_name__contains=search)|
                    Q(ingredient__contains=search)|
                    Q(type__contains=search)
                    )
                #並び替え
                if order == "new":
                    object_list = filter_object.order_by("-date")
                elif order == "old":
                    object_list = filter_object.order_by("date")
                #検索ワードのみの場合
                else:
                    object_list = filter_object.order_by("-date")
            elif order == "old":
                object_list = filter_object.order_by("date")
            else:
                object_list = filter_object.order_by("-date")
            return object_list



#他のユーザーのリスト
class EatUsersListView(ListView):
    model = Recipe
    paginate_by = 20
    login_url = "/signup/login/"
    template_name = "eat/recipe_list.html"

    def get_queryset(self):
        search = self.request.GET.get("search")
        order = self.request.GET.get("order")
        users_id = self.kwargs.get('users_id')
        users = User.objects.get(id=users_id)


        filter_object = Recipe.objects.filter(user=users_id)
        #非公開の投稿を表示させない
        if self.request.user.is_authenticated:
            if users == self.request.user:
                filter_object = filter_object.order_by("-date")
            elif users in self.request.user.follow.all():
                filter_object = filter_object.exclude(public="非公開")
            else:
                filter_object = filter_object.exclude(Q(public="非公開") | Q(public="友達のみ"))
        else:
            filter_object = filter_object.exclude(Q(public="非公開") | Q(public="友達のみ"))
        if search:
            filter_object = filter_object.filter(
                Q(user=users_id),
                Q(recipe_name__contains=search)|
                Q(ingredient__contains=search)|
                Q(type__contains=search))
            if order == "new":
                object_list = filter_object.order_by("-date")
            elif order == "old":
                object_list = filter_object.order_by("date")
            else:
                object_list = filter_object.order_by("-date")
        elif order == "old":
            object_list = filter_object.order_by("date")
        else:
            object_list = filter_object.order_by("-date")
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users_id = self.kwargs.get('users_id')
        users = User.objects.get(id=users_id)
        recipe_count = Recipe.objects.filter(user=users).count()
        follower_count = User.objects.filter(follow__username=users).count()
        context["recipe_count"] = recipe_count
        context["users"] = users
        context["follower_count"] = follower_count
        return context




class EatFindListView(ListView):
    model = Recipe
    paginate_by = 20
    login_url = "/signup/login/"
    template_name = "eat/recipe_find_list.html"

    def get_queryset(self):
        search = self.request.GET.get("search")
        order = self.request.GET.get("order")

        filter_object = Recipe.objects.all()

        #ログインしている場合
        if self.request.user.is_authenticated:
            #ログイン中
            #フォローしているユーザーの友達のみ公開の投稿を絞り込む
            filter_object = filter_object.filter(
                Q(user__in=self.request.user.follow.all(), public="友達のみ")|
                Q(public="公開")|
                Q(user=self.request.user)
                )
        #ログアウト中
        else:
            filter_object = filter_object.exclude(
                Q(public="非公開")|
                Q(public="友達のみ")
                )
        if search:
            filter_object = filter_object.filter(
                Q(recipe_name__contains=search)|

cook_css/eat/templates/eat/quote_create.html
{% extends "eat/recipe_create_form.html" %}

cook_css/eat/templates/eat/quote_recipe.html
{% extends "base_list.html" %}
{% load static %}
{% load humanize %}　

{% block body %}
{% block profile %}
{% endblock profile %}

{% block edit %}
{% endblock edit %}

{% block object__header %}
{{ block.super }}
{% endblock object__header %}
{% block object_content_and_icon %} 
{{ block.super }}
{% endblock object_content_and_icon %} 
</div>

<div class="form">
    <div class="form__content">
        <p>このレシピを参考にして作成しますか？</p>
        <a class="button a_margin" href="{{request.META.HTTP_REFERER}}" role="button">戻る</a>
        <a class="button a_margin" href="{% url 'eat:quote_create' object.id %}" role="button">作成</a>
    </div>
</div>


{% endblock body %}

cook_css/eat/templates/eat/recipe_create_form.html
{% extends "base.html" %}

{% block body %}

<div class="form create">
    <div class="form__content">
    <div>
    　<h4>新規作成</h4>
    </div>
  <form method = "post" enctype="multipart/form-data">
   {% csrf_token %}
   <table>
   {% for field in form %}
   <tr>
       <th>{{ field.label }}{% if field.field.required %} ※{% endif %}</th>
       <td>{{ field }}</td>
   </tr>
  {% endfor %}
</table>
    <div>
      <a class="button a_margin" href="{{request.META.HTTP_REFERER}}">戻る</a></button> 
      <button type="submit">保存</button>
    </div>
  </form>
  </div>
</div>

{% endblock %}

cook_css/eat/templates/eat/recipe_delete.html
{% extends 'base.html' %}

{% block body %}

<div class="delete detail">
    <div class="detail__content">
        <div class="title">本当に消去してよろしいですか？</div>
        <p>消去後は復元できません</p>
        <form method = "post">
            {% csrf_token %}
            <a class="button" href="{% url 'eat:detail' object.id %}" >戻る</a>
            <button type = "submit">消去</button>
        </form>        
    </div>
</div>

{% endblock %}

cook_css/eat/templates/eat/recipe_detail.html
{% extends "base_list.html" %}
{% load static %}
{% load humanize %}

{% block body %}

{% if object.quote == "有り" and object.quote_recipe == None %}
<div class="form">
    <div class="form__content">
        <p>参考にしたレシピは消去されました</p>
    </div>
</div>
{% elif object.quote == "有り" %}
<div class="quote__recipe">
    <p>参考にしたレシピ</p>
</div>
<div class="timeline"> 
        <div class="timeline__content">
            <div class="recipe-detail__icon">
                {% if object.user.icon  %}
                <img  class="profile__img" src="{{ object.quote_recipe.user.icon.url }}">
                {% else %}
                <img class="profile__img" src="{% static 'img/illustration-2541681_1280.jpg' %}">
                {% endif %}
                <a href = "{% url 'eat:users' object.quote_recipe.user.id %}">{{ object.quote_recipe.user }}</a>
            </div>    
            <div class="timeline__inner">
                <div class="title">
                    <a href="{% url 'eat:detail' object.quote_recipe.id %}">{{ object.quote_recipe.recipe_name }}</a>
                </div>
                <div class="timeline-img">
                    {% if object.photo %}
                        <img src="{{ object.quote_recipe.photo.url }}">
                    {% else %}
                        <img src="{% static 'img/smIMGL3647_TP_V.jpg' %}">
                    {% endif %}            
                </div>
                <div class="objects">
                    <div class="p">
                        <p>材料：{{ object.quote_recipe.ingredient }}</p>
                        <p>種類：{{ object.quote_recipe.type }}</p> 
                    </div>
                    <div class="count">
                        <div class="good">
                            {% if request.user in object.quote_recipe.good_user.all %}
                            <p><a href="{% url 'eat:good' object.quote_recipe.id %}"><span style="color:#FF0000">&hearts;</span></a>
                            {% else %}
                            <p><a href="{% url 'eat:good' object.quote_recipe.id %}"><span style="color:#FF0000">&#9825;</span></a>
                            {% endif %}
                            {{ object.quote_recipe.good_user.count }}
                        </div>
                        <div class="quote">
                            <a href="{% url 'eat:quote_detail' object.quote_recipe.id %}">参考cook:</a> {{ object.quote_user.count }}
                        </div>
                    </div>
                </div>
                <div class="time">
                    {{ object.quote_recipe.date | date:"Y/n/j"  }}
                </div>
            </div>
    </div>
</div>
{% endif %}






<div class="recipe-detail">
    <div class="recipe-detail__icon">
        {% if object.user.icon  %}
        <img  class="profile__img" src="{{ object.user.icon.url }}">
        {% else %}
        <img class="profile__img" src="{% static 'img/illustration-2541681_1280.jpg' %}">
        {% endif %}
        <a href = "{% url 'eat:users' object.user.id %}">{{ object.user }}</a>
    </div>
    <div class="recipe-detail__container">
        {% if object.quote == "有り" %}
        <div class="recipe-detail__content yellow">
        {% else %}
        <div class="recipe-detail__content">
        {% endif %}
            <div class="detail__img">
                {% if object.photo %}
                <img src="{{ object.photo.url }}" alt="">
                {% else %}
                <img src="{% static 'img/smIMGL3647_TP_V.jpg' %}">
                {% endif %}
            </div>
            <div class="objects">
                <div class="title">
                    {{ object.recipe_name }}
                </div>
                {% if object.memo %}
                <div class="memo">
                    <div class="title">--memo--</div>
                    <div class="content">{{ object.memo | linebreaksbr }}</div>
                </div>
                {% endif %}
                <div class="p">
                    <p>材料：{{ object.ingredient }}</p>
                    <p>種類：{{ object.type }}</p>
                </div>
                {% if object.site %}
                <div class="url">
                    <p>参考サイト:</p><p>{{ object.site| truncatechars:50 | urlize }}</p>
                </div>
                {% endif %}
                <div class="count">
                    <div class="good">
                        {% if request.user in object.good_user.all %}
                        <p><a href="{% url 'eat:good' object.id %}"><span style="color:#FF0000">&hearts;</span></a>
                        {% else %}
                        <p><a href="{% url 'eat:good' object.id %}"><span style="color:#FF0000">&#9825;</span></a>
                        {% endif %}
                        {{ object.good_user.count }}&nbsp;&nbsp;&nbsp;&nbsp;
                    </div>
                    <div class="quote">
                        {% if  object.quote == "有り" %}
                        <!-- ログインユーザーと投稿者が同じ場合、Urlは表示しない-->
                        {% elif request.user == object.user %}
                        参考cook:{{ object.quote_user.count | intword }}
                        {% else %}
                        <!-- 自分の投稿じゃない場合と投稿自体が参考cookじゃない場合、urlにアクセス可能　-->
                        <a href="{% url 'eat:quote_detail' object.id %}">参考cook:</a> {{ object.quote_user.count | intword }}
                        {% endif %}
                    </div>
                </div>
            </div>    
        </div>
        <div class="recipe-detail__day">{{ object.date }}</div>
        <div class="recipe-detail__button">
             <a class="button a_margin" href = "{{request.META.HTTP_REFERER}}">戻る</a>
             {% if request.user == object.user %}
             <a class="button a_margin" href = "{% url 'eat:update' object.id %}">編集</a>
             <a class="button a_margin" href="{% url 'eat:delete' object.id %}">消去</a> 
             {% endif %}          
        </div>
    </div>    
</div>





{% if object_list %}
<div class="quote__recipe quote__recipe_margin">
    <p>このレシピの参考cook</p>
</div>
{% block object %}
{{ block.super }}
{% endblock object %}

{% endif %}

{% endblock %}

cook_css/eat/templates/eat/recipe_find_list.html
{% extends 'eat/recipe_timeline_list.html' %}
{% load static %}
{% load humanize %}



{% block object %}
{% if not object_list %}
<div class="form">
    <div class="form__content">
        <p>該当する項目は、ありませんでした</p>
    </div>
</div>
{% else %}
{{ block.super }}
{% endif %}
{% endblock object %} 

cook_css/eat/templates/eat/recipe_good_users_list.html
{% extends "base_list.html" %}
{% load static %}
{% load humanize %}

cook_css/eat/templates/eat/recipe_list.html
{% extends "base_list.html" %}
{% load static %}
{% load humanize %}　

{% block body %}

{% block profile %}
{{ block.super }}
{% endblock profile %}


{% if request.GET.deletes %}
<form action="" method="post">
    {% csrf_token %}
    <div class="selective_delection_button">
            <a class="button" href="{% url 'eat:index' %}" role="button">戻る</a>
            <button type="submit">消去</button>
    </div>
    {% block object__header %}
    <div class="timeline selective_deletion"> 
    {% endblock object__header %}   
        {% for object in object_list %}
        <div class= "checkbox">
            <input type="checkbox" name="delete" value="{{ object.pk }}">
        </div>
        <div class="timeline__content">  
            {% block object_content %}
            {{ block.super }}
            {% endblock object_content %}         
        </div>
</form>
    {% endfor %}
</div>


{% elif not object_list and request.user.id == users.id %}
<div class="form">
    <div class="form__content">
        <p>レシピを登録してみよう</p>
    </div>
</div>


{% elif not object_list and request.user.id != users.id %}
<div class="form">
    <div class="form__content">
        <p>投稿がありません</p>
    </div>
</div>
 

{% elif object_list and not request.GET.deletes %}
{% block edit %}
{{ block.super }}
{% endblock edit %}
    <div class="mylist">
        {% if users == request.user %}
        {% if recipe_count >= 2 and not request.GET.deletes and object_list %}
        <div class="mylist__edit">
            <form action="" method="get">
                <button name = "deletes" value = "deletes" class="btn btn-outline-success" type="submit">選択消去</button>
            </form>
        </div> 
        {% endif %}       
        {% endif %}


        <div class="mylist__img">
            {% for object in object_list %}
                {% if object.photo %}
                    <a href="{% url 'eat:detail' object.id %}">
                        <img src="{{ object.photo.url }}">
                    </a>
                {% else %}
                    <a href="{% url 'eat:detail' object.id %}">
                        <img src="{% static 'img/smIMGL3647_TP_V.jpg' %}">
                    </a>
                {% endif %}
            {% endfor %}              
        </div>
    </div>
{% endif %}

{% block pagination %}
{{ block.super }}
{% endblock pagination %}

{% endblock %}

cook_css/eat/templates/eat/recipe_timeline_list.html
{% extends 'base_list.html' %}
{% load static %}
{% load humanize %}


{% block profile %}
{% endblock profile %}

{% block edit_form %}  
<form action = "{% url 'eat:timeline' %}" method = "get" class = "form-row">
{% endblock edit_form %} 

cook_css/eat/templates/eat/recipe_update_form.html
{% extends "base.html" %}

{% block body %}

<div class="form create">
    <div class="form__content">
    <div>
    　<h4>編集</h4>
    </div>
  <form method = "post" enctype="multipart/form-data">
   {% csrf_token %}
    <table>
      {{ form }}
    </table>
    <div>
      <a class="button" href="{% url 'eat:detail' object.id %}">戻る</a>
      <button type="submit">保存</button>
    </div>
  </form>
  </div>
</div>

{% endblock %}