cook_css/cook_css/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("eat/", include("eat.urls")),
    path("signup/", include("signup.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cook_css/eat/urls.py
from django.contrib import admin
from django.urls import path
from signup.models import User
from .views import EatListView, EatDetailView, EatCreateView, EatUpdateView, EatDeleteView, EatTimeLineListView, EatUsersListView, EatFindListView, EatGoodUsersListView, good, EatQuoteDetailView, EatQuoteCreateView

app_name = "eat"

urlpatterns = [
    path('index/', EatListView.as_view(), name="index"),
    path('detail/<int:pk>/', EatDetailView.as_view(), name="detail"),
    path('create/', EatCreateView.as_view(), name="create"),
    path('update/<int:pk>/', EatUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', EatDeleteView.as_view(), name="delete"),
    path('timeline/', EatTimeLineListView.as_view(), name="timeline"),
    path('users/<int:users_id>/', EatUsersListView.as_view(), name="users"),
    path('find/', EatFindListView.as_view(), name="find"),
    path('<int:pk>/', good, name="good"),
    path('detail/quote/<int:pk>/', EatQuoteDetailView.as_view(), name="quote_detail"),
    path('create/quote/<int:pk>/', EatQuoteCreateView.as_view(), name="quote_create"),
    #path('<int:pk>', GoodUpdateView.as_view(), name = 'good')
    path('list/<int:users_id>/', EatGoodUsersListView.as_view(), name='good_users_list')

]
 

cook_css/signup/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from .views import follow, follow_permission, follow_reject, SignupCreateView, SignupLoginView, SignupDetailView, SignupUpdateView, SignupPasswordChangeView, SignupDeleteView, follow, SignupFollowListView, SignupFollowerListView, FollowRequestView


app_name = "signup"

urlpatterns = [
    path('<int:pk>/', follow, name="follow"),
    path('<int:pk>/permission/', follow_permission, name="follow_permission"),
    path('<int:pk>/reject/', follow_reject, name="follow_reject"),
    path('follow/request/<int:users_id>/', FollowRequestView.as_view(), name="follow_request_list"),
    path('follow/<int:users_id>/', SignupFollowListView.as_view(), name="follow_list"),
    path('follower/<int:users_id>/', SignupFollowerListView.as_view(), name="follower_list"),
    path('new/', SignupCreateView.as_view(), name="new"),
    path('login/', SignupLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(template_name='signup/top.html'), name="logout"),
    path('detail/', SignupDetailView.as_view(), name="detail"),
    path('update/<int:pk>/', SignupUpdateView.as_view(), name="update"),
    path('change/', SignupPasswordChangeView.as_view(), name="changepass"),
    path('delete/<int:pk>/', SignupDeleteView.as_view(), name="delete"),
    path('password_reset/', PasswordResetView.as_view(success_url=reverse_lazy('signup:password_reset_done')), name="password_reset"),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(success_url=reverse_lazy('signup:password_reset_complate')), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complate"),
    path('top/', TemplateView.as_view(template_name='signup/top.html'), name="top"),

    #path("register/", signupregister, name = "register"),
    #path("register/", SignupDetailView.as_view(), name = "register"),
]

cook_css/signup/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.

class User(AbstractUser):
    email = models.EmailField("メールアドレス")
    icon = models.ImageField("アイコン", upload_to="Media", blank=True, null=False)
    follow = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="follow_user")
    follow_request = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="follow_request_user")

cook_css/signup/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    #icon = forms.ImageField(label = "アイコン", required = False)
    class Meta:
        model = User
        #fields = ("username", "icon")
        fields = ("username","email")

class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ("username", "icon", "email")


    # 入力後戻った時にパスワードも入力済みにする　
class CustomUpdateForm(UserChangeForm):

    class Meta:
        model = User
        fields = ['is_active']

cook_css/signup/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib import messages


from django.views.generic import FormView, TemplateView, UpdateView, ListView
#from django.views.generic.base import View
from django.views import View

from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from signup.models import User
from signup.forms import CustomUserCreationForm, CustomUserChangeForm, CustomUpdateForm
from eat.models import Recipe


# Create your views here.


class LogoutRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("eat:index")
        return super().dispatch(*args, **kwargs)

class OnlyMixin(UserPassesTestMixin):

    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser




def follow(request, *args, **kwargs):
    #閲覧中のユーザー取得
    look_user = User.objects.get(id=kwargs['pk'])

    if request.user.is_authenticated:
        print("b")
        #自分はフォローできないようにする
        if look_user != request.user:
            #閲覧中のユーザーをフォローしている場合
            if User.objects.filter(username=request.user, follow=look_user).exists():
                #request.userのfollowフィールドから閲覧中のユーザーを消去
                print("a")
                request.user.follow.remove(look_user)
                request.user.save()
            elif look_user in request.user.follow_request.all():
                request.user.follow_request.remove(look_user)
                request.user.save()
            #フォローしていない場合
            elif request.user in look_user.follow_request.all():
                look_user.follow_request.remove(request.user)
                look_user.save()
            else:
                #request.userのfollowフィールドに閲覧中のユーザーを追加
                look_user.follow_request.add(request.user)
                look_user.save()
                #request.user.follow.add(look_user)
                #request.user.save()
                #直前のページにリダイレクト
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            return redirect("eat:index")
    else:
        return redirect("signup:login")

#フォローリクエストの承認
def follow_permission(request, *args, **kwargs):
    #閲覧中のユーザー取得
    look_user = User.objects.get(id=kwargs['pk'])

    if request.user.is_authenticated:
        look_user.follow.add(request.user)
        look_user.save()
        request.user.follow_request.remove(look_user)
        look_user.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return redirect("signup:login")

def follow_reject(request, *args, **kwargs):
    #閲覧中のユーザー取得
    look_user = User.objects.get(id=kwargs['pk'])

    if request.user.is_authenticated:
        request.user.follow_request.remove(look_user)
        request.user.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return redirect("signup:login")

class FollowRequestView(ListView):
    model = User
    template_name = "signup/signup_follow_request_list.html"

    def get_queryset(self, **kwargs):
        #閲覧中のユーザー取得
        visited_user_id = self.kwargs.get('users_id')
        visited_user = User.objects.get(id=visited_user_id)

        if self.request.user:
            object_list = self.request.user.follow_request.all()
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users_id = self.kwargs.get('users_id')
        users = User.objects.get(id=users_id)
        recipe_count = Recipe.objects.filter(user=users).count()
        follower_count = User.objects.filter(follow__username=users).count()
        context["recipe_count"] = recipe_count
        context["users"] = users
        context["follower_count"] = follower_count
        return context



class SignupFollowListView(ListView):
    model = User
    template_name = "signup/signup_follow_list.html"

    def get_queryset(self, **kwargs):
        #閲覧中のユーザー取得
        visited_user_id = self.kwargs.get('users_id')
        visited_user = User.objects.get(id=visited_user_id)

        #自分のフォローを表示
        if visited_user == self.request.user:
            object_list = self.request.user.follow.all()

        #閲覧中のユーザーのフォローを表示
        else:
            object_list = visited_user.follow.all()
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users_id = self.kwargs.get('users_id')
        users = User.objects.get(id=users_id)
        recipe_count = Recipe.objects.filter(user=users).count()
        follower_count = User.objects.filter(follow__username=users).count()
        context["recipe_count"] = recipe_count
        context["users"] = users
        context["follower_count"] = follower_count
        return context


class SignupFollowerListView(ListView):
    model = User
    template_name = 'signup/signup_follow_list.html'

    def get_queryset(self, **kwargs):
        #閲覧中のユーザー取得
        visited_user_id = self.kwargs.get('users_id')
        visited_user = User.objects.get(id=visited_user_id)

        #閲覧中のユーザーのフォロワーを表示
        if visited_user == self.request.user:
            object_list = User.objects.filter(follow__username=self.request.user)
        #自分のフォロワーを表示
        else:
            object_list = User.objects.filter(follow__username=visited_user)
        return object_list



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users_id = self.kwargs.get('users_id')
        users = User.objects.get(id=users_id)
        recipe_count = Recipe.objects.filter(user=users).count()
        follower_count = User.objects.filter(follow__username=users).count()
        context["recipe_count"] = recipe_count
        context["users"] = users
        context["follower_count"] = follower_count
        return context



class SignupCreateView(LogoutRequiredMixin, FormView):
    form_class = CustomUserCreationForm
    template_name = "signup/signup_new.html"
    success_url = reverse_lazy("signup:login")


    def form_valid(self, form):
        button = self.request.POST.get("next")
        if button == "back":
            return render(self.request, "signup/signup_new.html", {"form":form})
        elif button == "confirm":
            return render(self.request, "signup/signup_regist.html", {"form":form})
        elif button == "regist":
            form.save()
            messages.success(self.request, "会員登録が完了しました。ユーザー名とパスワードを入力してログインしてください")
            return super().form_valid(form)
        else:
            return redirect("signup:login")
        return super().form_valid(form)


class SignupLoginView(LogoutRequiredMixin, LoginView):
    template_name = "login.html"

    def form_valid(self, form):
        messages.success(self.request, "ログインしました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "ログインできませんでした。正しいパスワードとユーザー名を入力してください")
        return super().form_invalid(form)




class SignupDetailView(LoginRequiredMixin, TemplateView):
    template_name = "signup/signup_detail.html"
    login_url = "/signup/login/"


class SignupUpdateView(LoginRequiredMixin, OnlyMixin, UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = "signup/signup_update.html"
    success_url = reverse_lazy("eat:index")
    login_url = "/signup/login/"

    def form_valid(self, form):
        messages.success(self.request, "ユーザー情報を変更しました")
        return super().form_valid(form)


class SignupPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = "signup/signup_PasswordChange.html"
    success_url = reverse_lazy("eat:index")
    login_url = "/signup/login/"

    def form_valid(self, form):
        messages.success(self.request, "パスワードを変更しました")
        return super().form_valid(form)


class SignupDeleteView(LoginRequiredMixin, OnlyMixin, FormView):
    model = User
    form_class = CustomUpdateForm
    template_name = "signup/signup_delete.html"
    success_url = reverse_lazy("signup:new")
    login_url = "/signup/login/"

    def form_valid(self, form):
        self.request.user.is_active = False
        self.request.user.save()
        messages.success(self.request, "退会しました。再度アプリを利用するには会員登録が必要です")
        return super().form_valid(form)

cook_css/signup/templates/signup/signup_PasswordChange.html
{% extends "base.html" %}

{% block body %}

<div class="form">
 <div class="form__content">
  <div class="title">
   <h4>パスワード変更</h4>
  </div>

  <form action = "" method = "post">
   {% csrf_token %}
  <table class="signup">
   {% for field in form %}
   <tr>
    <th class="regist"> 
     <label for="field.id_for_lavel">
       {{ field.label_tag }}
     </label>
    </th>
    <td>
       {{ field }}
    </td>
    </tr>
   {% endfor %}

   {% if form.errors %}
    <div>
     {% for field in form %}
       <p>{{ field.errors }}</p>
     {% endfor %}
    </div>
   {% endif %}
  </table>
  <div>
    <a class="button" href = "{{request.META.HTTP_REFERER}}">戻る</a>
    <button name="next" value="confirm" type="submit">変更</button>
  </div>
  </form>
 </div>
</div>

{% endblock %}

cook_css/signup/templates/signup/signup_delete.html
{% extends "base.html" %}

{% block body %}

<div class="form">
    <div class="form__content">
        <div class="title">
            <h4>退会の手続き</h4>
        </div>
        <div>
            <p>退会すると、今までの投稿も削除されます</p>
            <p>よろしいですか？</p>
        </div>
  <form action = "" method = "post">
  {% csrf_token %}
  <table>
  {% csrf_token %}
  {% for field in form %}
  {{field.as_hidden}}
  {% endfor %}
  </table>

  <div>
  <a class="button" href="{{request.META.HTTP_REFERER}}"role="button">戻る</a>
  <button name="choise" value="delete" type="submit" class="btn btn-danger">退会</button>
  </div>
  </form>
</div>
</div>

</div>
</div>

{% endblock %}

cook_css/signup/templates/signup/signup_detail.html
{% extends 'base.html' %}

{% block body %}

<div class="detail">
    <div class="detail__content">
        <div class="title">編集</div>
        <ul class="a-navy">
            <li><a href="{% url 'signup:update' user.id %}" >ユーザー情報変更</a></li>
            <li><a href="{% url 'signup:changepass' %}" >パスワード変更</a></li>
            <li><a href="{% url 'signup:delete' user.id %}" >退会の手続き</a></li>
        </ul>
        <a class="button" href = "{{request.META.HTTP_REFERER}}">戻る</a>
    </div>
</div>

{% endblock %}

cook_css/signup/templates/signup/signup_follow_list.html
{% extends "base_list.html" %}
{% load static %}

{% block body %}


 {% block profile %}
  {{ block.super }}
 {% endblock profile %}




<div class="follow_list">
  {% for object in object_list %}
  {% block follow_list %}
 <div class="follow_list__content">
   <div class="left">
    {% if object.icon  %}
      <img class="profile__img" src="{{ object.icon.url }}" class="rounded-circle " style="width: 100px;height: 100px;">
    {% else %}
      <img  class="profile__img" src="{% static 'img/illustration-2541681_1280.jpg' %}" class="rounded-circle " style="width: 100px;height: 100px;">
    {% endif %}
   </div>
   <div class="right">
     <div class="name">
      {% if request.user.id == object.id %}
      <a href = "{% url 'eat:index' %}">{{ object }}</a>
      {% else %}
      <a href = "{% url 'eat:users' object.id %}">{{ object }}</a>
      {% endif %}
     </div>
     {% endblock follow_list %}
     <div class="right_button">
      {% if object == request.user %}
      {% elif object in request.user.follow.all %}
        <a class="button" href = "{% url 'signup:follow' users.id %}">フォロー中</a>
      {% elif request.user in object.follow_request.all %}
        <a class="button" href = "{% url 'signup:follow' users.id %}">フォロー許可待ち</a>
      {% else %}
        <a class="button" href = "{% url 'signup:follow' users.id %}">フォロー</a>
      {% endif %}       
     </div>
   </div>
  </div>
  {% endfor %}
</div>




{% endblock body %}

cook_css/signup/templates/signup/signup_follow_request_list.html
{% extends "signup/signup_follow_list.html" %}
{% load static %}


{% block body %}

{% block profile %}
{{ block.super }}
{% endblock profile %}

{% if not request.user.follow_request.all %}

  <div class="form follow_request">
    <div class="form__content">
      <div>
        <p>現在<br>フォローリクエストは<br>ありません</p>
      </div>
    </div>
  </div>

{% else %}

<div class="follow_list">
  {% for object in object_list %}
  {% block follow_list %}
    {{ block.super }}
  {% endblock follow_list %}
     <div class="button">
        <button type="button"><a href = "{% url 'signup:follow_permission' object.id %}">許可</a></button>
        <button type="button"><a href = "{% url 'signup:follow_reject' object.id %}">拒否</a></button>     
     </div>
   </div>
  </div>
  {% endfor %}
</div>

{% endif %}

{% endblock %}

cook_css/signup/templates/signup/signup_new.html
  
{% extends "base.html" %}

{% block body %}


<div class="form">
    <div class="form__content">
        <div class="title">
            <h4>会員登録</h4>
        </div>
        <form action = "" method = "post">
          {% csrf_token %}
          <table class="signup">
            {% for field in form %}
            <tr>
                <th>
                    <label for="field.id_for_label">
                      {{ field.label }}
                    </label>
                </th>
                <td>
                    {{ field }}
                </td>
            </tr>
            {% endfor %}
        
            {% if form.errors %}
            <div>
            {% for field in form %}
              <p>{{ field.errors }}</p>
            {% endfor %}
            {% endif %}
            </div>       
          </table>
          <div>
            <a class="button" href = "{{request.META.HTTP_REFERER}}">戻る</a>
            <button name="next" value="confirm" type="submit" class="btn btn-info">確認</button>        
          <div>
        </form>
        </div>
        </div>
        
    </div>
</div>
    
{% endblock %}

cook_css/signup/templates/signup/signup_regist.html
{% extends "base.html" %}

{% block body %}

<div class="form">
    <div class="form__content">
        <div class="title">
            <h4>登録フォーム</h4>
        </div>
        <table class="signup">
            <tr>
                <th class="regist"> 
                    <label for="field.id_for_label">
                        ユーザー名：
                    </label>
                </th>
                <td>
                    {{ form.cleaned_data.username }}
                </td>
            </tr>
            <tr>
                <th class="regist">                           
                    <label for="field.id_for_label">
                        メールアドレス：
                    </label>
                </th>
                <td>
                    {{ form.cleaned_data.email }}
                </td>
            </tr>
            <tr>
                <th class="regist">
                    <label for="field.id_for_label">
                        パスワード：
                    </label>
                </th>
                <td>
                    ******
                </td>
            </tr>
        </table>
    <form action = "" method = "post">
      {% csrf_token %}
    <table>
      {% csrf_token %}
      {% for field in form %}
        {{field.as_hidden}}
      {% endfor %}
    </table>
    <div>
      <button name="next" value="back" type="submit">戻る</button>
      <button name="next" value="regist" type="submit">登録</button>
    </div>
    </form>

    </div>
</div>

{% endblock %}

cook_css/signup/templates/signup/signup_update.html
{% extends "base.html" %}

{% block body %}
<div class="form">
    <div class="form__content">
        <div class="title">
            <h4>ユーザー情報変更フォーム</h4>
        </div>
<form action = "" method = "post">
    {% csrf_token %}
    <table class="signup">
      {% for field in form %}
      <tr>
          <th>
              <label for="field.id_for_label">
                {{ field.label }}
              </label>
          </th>
          <td>
              {{ field }}
          </td>
      </tr>
      {% endfor %}
  
      {% if form.errors %}
      <div>
      {% for field in form %}
        <p>{{ field.errors }}</p>
      {% endfor %}
      {% endif %}
      </div>       
    </table>
    <div>
      <a class="button" href = "{{request.META.HTTP_REFERER}}">戻る</a>
      <button  type="submit" class="btn btn-info">変更</button>
    <div>
  </form>
</div>
</div>

</div>
</div>

{% endblock %}

cook_css/signup/templates/signup/top.html
{% extends "base.html" %}
{% load static %}

{% block body %}
      <div class="home">
        <div class="home__card">
          <div class="home__img">
            <img class="img-cook" src="{% static 'img/food-3048440_1280.jpg' %}" alt="">
          </div>
          <div class="home_container">
            <h3 class="home_title">CooooK!は料理登録サイトです</h3>
            <p class="home_description">レシピを検索してみよう</p>
            <form class="home__search search" method = "get" action = "{% url 'eat:find' %}">
              <input name="search" class="search__winddow" value = "{{ request.GET.search }}" placeholder="材料,料理名,種類"></input>
              <button class="search__button"　type="submit">Search</button>
            </form>
          </div>
        </div>
      </div>

{% endblock %}