cook_css/cook_css/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("eat/", include("eat.urls")),
    path("signup/", include("signup.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cook_css/eat/urls.py
from django.contrib import admin
from django.urls import path
from signup.models import User
from .views import EatListView, EatDetailView, EatCreateView, EatUpdateView, EatDeleteView, EatTimeLineListView, EatUsersListView, EatFindListView, EatGoodUsersListView, good, EatQuoteDetailView, EatQuoteCreateView

app_name = "eat"

urlpatterns = [
    path('index/', EatListView.as_view(), name="index"),
    path('detail/<int:pk>/', EatDetailView.as_view(), name="detail"),
    path('create/', EatCreateView.as_view(), name="create"),
    path('update/<int:pk>/', EatUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', EatDeleteView.as_view(), name="delete"),
    path('timeline/', EatTimeLineListView.as_view(), name="timeline"),
    path('users/<int:users_id>/', EatUsersListView.as_view(), name="users"),
    path('find/', EatFindListView.as_view(), name="find"),
    path('<int:pk>/', good, name="good"),
    path('detail/quote/<int:pk>/', EatQuoteDetailView.as_view(), name="quote_detail"),
    path('create/quote/<int:pk>/', EatQuoteCreateView.as_view(), name="quote_create"),
    #path('<int:pk>', GoodUpdateView.as_view(), name = 'good')
    path('list/<int:users_id>/', EatGoodUsersListView.as_view(), name='good_users_list')

]
 

cook_css/signup/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from .views import follow, follow_permission, follow_reject, SignupCreateView, SignupLoginView, SignupDetailView, SignupUpdateView, SignupPasswordChangeView, SignupDeleteView, follow, SignupFollowListView, SignupFollowerListView, FollowRequestView


app_name = "signup"

urlpatterns = [
    path('<int:pk>/', follow, name="follow"),
    path('<int:pk>/permission/', follow_permission, name="follow_permission"),
    path('<int:pk>/reject/', follow_reject, name="follow_reject"),
    path('follow/request/<int:users_id>/', FollowRequestView.as_view(), name="follow_request_list"),
    path('follow/<int:users_id>/', SignupFollowListView.as_view(), name="follow_list"),
    path('follower/<int:users_id>/', SignupFollowerListView.as_view(), name="follower_list"),
    path('new/', SignupCreateView.as_view(), name="new"),
    path('login/', SignupLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(template_name='signup/top.html'), name="logout"),
    path('detail/', SignupDetailView.as_view(), name="detail"),
    path('update/<int:pk>/', SignupUpdateView.as_view(), name="update"),
    path('change/', SignupPasswordChangeView.as_view(), name="changepass"),
    path('delete/<int:pk>/', SignupDeleteView.as_view(), name="delete"),
    path('password_reset/', PasswordResetView.as_view(success_url=reverse_lazy('signup:password_reset_done')), name="password_reset"),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(success_url=reverse_lazy('signup:password_reset_complate')), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complate"),
    path('top/', TemplateView.as_view(template_name='signup/top.html'), name="top"),

    #path("register/", signupregister, name = "register"),
    #path("register/", SignupDetailView.as_view(), name = "register"),
]

cook_css/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;400&family=Pacifico&display=swap" rel="stylesheet">
</head>
<body>
  <div id="global-container">
    <div id="container">
      <header class="header">
        <div class="header__inner">
          <div class="header__left">
            <div class="header__logo">
              <img src="{% static 'img/food-freebiesgallery.png' %}" alt="">
              <a class="cook" href="{% url 'signup:top' %}">CooooK!</a>
            </div>
            {% if user.is_authenticated %}
            <div class="header__li">
              <ul>
                <li><a href= "{% url 'eat:timeline' %}" >今日のごはん</a></li>
                <li><a href= "{% url 'eat:index' %}" >マイページ</a></li>
                <li><a href="{% url 'eat:create' %}">新規作成</a></li>
                <li><a href = "{% url 'signup:detail' %}">会員情報</a></li>
                <li><a href = "{% url 'signup:logout' %}">ログアウト</a></li>
              </ul>
            </div>
          </div>
          <div class="header__right">
            {% if "find" in request.path or "timeline" in request.path or "index" in request.path or "users" in request.path or "list" in request.path %}
            {% if "find" in request.path %}
             <form class="header__search search" action = "{% url 'eat:find' %}" method = "get" class="search">
            {% elif "timeline" in request.path %}
             <form class="header__search search" action = "{% url 'eat:timeline' %}" method = "get" class="search">
            {% elif "index" in request.path %}
             <form class="header__search search" action = "{% url 'eat:index' %}" method = "get" class="search">
            {% elif "users" in request.path %}
             <form class="header__search search" action = "{% url 'eat:users' users.id %}" method = "get" class="search">
            {% elif "list" in request.path %}
            <form class="header__search search" action = "{% url 'eat:good_users_list' users.id %}" method = "get" class="search">
            {% else %}
            {% endif %}
            <input name="search" class="search__winddow" value = "{{ request.GET.search }}" placeholder="材料,料理名,種類"></input>
            <!-- 並び替え設定時 -->
            {% if request.GET.order %}
            <input class="search__winddow" name = "order" value = "{{ request.GET.order }}" type = "hidden">
            {% endif %}
            <button class="search__button" type="submit">Search</button>
          </form>         
          {% endif %}

           {% else %}
           <div class="header__li">
            <ul class="header__logout">
              <li><a href = "{% url 'signup:new' %}">会員登録</a></li>
              <li><a href = "{% url 'signup:login' %}">ログイン</a></li>
            </ul>
          </div>
        </div>
        <div class="header__right">
          {% endif %}


            <!-- <form class="search" method = "get" action = "{% url 'eat:find' %}">
              <input name="search" class="search__winddow" value = "{{ request.GET.search }}" placeholder="材料,料理名,種類"></input>
              <button class="search__button"　type="submit">Search</button>
            </form> -->
            <button class="mobile-menu_button">
              <span></span>
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
        <div class="header__bottom outview">
          <ul>
          {% if user.is_authenticated %}
          <li><a href= "{% url 'eat:timeline' %}" >今日のごはん</a></li>
          <li><a href= "{% url 'eat:index' %}" >マイページ</a></li>
          <li><a href="{% url 'eat:create' %}">新規作成</a></li>
          <li><a href = "{% url 'signup:detail' %}">会員情報</a></li>
          <li><a href = "{% url 'signup:logout' %}">ログアウト</a></li>
          
      
          {% if "find" in request.path or "timeline" in request.path or "index" in request.path or "users" in request.path or "list" in request.path %}
            <li>
            {% if "find" in request.path %}
             <form class= "search" action = "{% url 'eat:find' %}" method = "get" class="search">
            {% elif "timeline" in request.path %}
             <form class= "search" action = "{% url 'eat:timeline' %}" method = "get" class="search">
            {% elif "index" in request.path %}
             <form class= "search" action = "{% url 'eat:index' %}" method = "get" class="search">
            {% elif "users" in request.path %}
             <form class= "search" action = "{% url 'eat:users' users.id %}" method = "get" class="search">
            {% elif "list" in request.path %}
            <form class= "search" action = "{% url 'eat:good_users_list' users.id %}" method = "get" class="search">
            {% else %}
            {% endif %}
            <input name="search" class="search__winddow" value = "{{ request.GET.search }}" placeholder="材料,料理名,種類"></input>
            <!-- 並び替え設定時 -->
            {% if request.GET.order %}
            <input class="search__winddow" name = "order" value = "{{ request.GET.order }}" type = "hidden">
            {% endif %}
            <button class="search__button" type="submit">Search</button>
          </form> 
        </li>        
          {% endif %}
          {% else %}
             <li><a href = "{% url 'signup:new' %}">会員登録</a></li>
             <li><a href = "{% url 'signup:login' %}">ログイン</a></li>
         {% endif %}
        </ul>
        </div>

        {% if messages %}
        {% for message in messages %}
        {% if message.tags == "error" %}
        <div class="alert alert-warning" role="alert">
          {{ message }}
        {% else %}
        <div class="alert alert-success" role="alert">
          {{ message }}
        {% endif %}
        <button type="button" class="alert-button close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% endfor %}
        {% endif %}
      </header>


      
      {% block body %}

      {% endblock %}


      <footer>
        <div class="sitemap">
          <div class="sitemap__container">
          <div class="sitemap__title">Sitemap</div>
          <div class="sitemap__content">
            <div class="sitemap__subtitle">
              <a href="{% url 'signup:top' %}">トップページ</a>
            </div>
            <ul>
              <li class="sitemap__li">サイトの説明</li>
            </ul>
          </div>
          <div class="sitemap__content">
            <div class="sitemap__subtitle">
              <a href="{% url 'eat:index' %}">マイページ</a>
              </div>
            <ul>
              <li class="sitemap__li">
                <a href="{% url 'eat:index' %}">レシピ一覧</a>
              </li>
              <li class="sitemap__li">
                <a href="{% url 'eat:create' %}">新規作成</a>
              </li>
              <li class="sitemap__li">プロフィール</li>
            </ul>
          </div>
          {% if user.is_authenticated %}
          <div class="sitemap__content">
            <div class="sitemap__subtitle">
              <a href="{% url 'eat:timeline' %}">今日のごはん</a>
            </div>
          </div>
          <div class="sitemap__content">
            <div class="sitemap__subtitle">
              <a href="{% url 'signup:detail' %}">会員情報変更</a>
            </div>
            <ul>
              <li class="sitemap__li">
                <a href="{% url 'signup:update' user.id %}">ユーザー情報変更</a>
              </li>
              <li class="sitemap__li">
                <a href="{% url 'signup:changepass' %}">パスワード変更</a>
              </li>
              <li class="sitemap__li">
                <a href="{% url 'signup:delete' user.id %}">退会の手続き</a>
              </li>
            </ul>
          </div>
          {% else %}
          <div class="sitemap__content">
            <div class="sitemap__subtitle">
              <a href="{% url 'signup:new' %}">会員登録</a>
            </div>
          </div>
          <div class="sitemap__content">
            <div class="sitemap__subtitle">
              <a href="{% url 'signup:password_reset' %}">パスワードをお忘れの方</a>
            </div>
          </div>
          {% endif %}
        </div>
        </div>
      </footer>


    </div>
  </div>

  </div>



  <script src="{% static 'scripts/main.js' %}"></script>
</body>
</html>

cook_css/templates/base_list.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}　

{% block body %}



{% block profile %}
<div class="profile">
    <div class="profile__content">
        <div class="profile__left">
            {% if users.icon %}
                <img class="profile__img" src="{{ users.icon.url }}" alt="プロフィール画像">
            {% else %}
                <img class="profile__img" src="{% static 'img/illustration-2541681_1280.jpg' %}" alt="プロフィール画像">
            {% endif %}
        </div>
        <div class="profile__center">
            <div class="title">
                {% if request.user.id == users.id %}
                    <div class="name"><a href="{% url 'eat:index' %}">{{ users.username }}</a></div>
                {% else %}
                    <div class="name"><a href="{% url 'eat:users' users.id %}">{{ users.username }}</a></div>
                {% endif %}
                <div class="profile__edit__follow">
                    {% if request.user.id == users.id %}
                        <a class="button" href = "{% url 'signup:detail' %}">編集</a>
                    {% else %}
                        <div class="follow__button">
                            {% if users in request.user.follow.all %}
                                <a class="button" href = "{% url 'signup:follow' users.id %}">フォロー中</a>
                            {% elif request.user in users.follow_request.all %}
                                <a class="permit button" href = "{% url 'signup:follow' users.id %}">フォロー許可待ち</a>
                            {% else %}
                                <a class="button" href = "{% url 'signup:follow' users.id %}">フォロー</a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="profile__count">
                <p class="profile__list">レシピの数：{{ recipe_count }}</p>
                <ul>
                    <li><a href = "{% url 'signup:follow_list' users.id %}">フォロー</a>：{{ users.follow.count }}</li>
                    <li><a href = "{% url 'signup:follower_list' users.id %}">フォローワー</a>：{{ follower_count }}</li>
                    {% if request.user.id == users.id %}
                    <li><a href = "{% url 'signup:follow_request_list' users.id %}">リクエスト</a>：{{ users.follow_request.count }}</li>
                    {% endif %}
                </ul>
                <p class="profile__list"><a href = "{% url 'eat:good_users_list' users.id %}">いいね一覧</a></p>
            </div>
        </div>
        <div class="profile__right">
            <p>開始日：{{ users.date_joined | date:"Y/n/j" }}</p>
        </div>
    </div>
</div>
{% endblock profile %}

{% block edit %}
<div class="sort"> 
        {% block edit_form %}  
        {% if "index" in request.path %}
        <form action = "{% url 'eat:index' %}" method = "get">
        {% else %}
        <form action = "{% url 'eat:users' users.id %}" method = "get">
        {% endif %}
        {% endblock edit_form %} 
          {% if object_list %}
          <div class="sort__content">
            <div class="select">
              <select name = "order">
                {% if request.GET.order == 'old' %}
                <option value="new" label='新しい順'></option>
                <option selected value="old" label='古い順'></option>
                {% else %}
                <option selected value="new" label='新しい順'></option>
                <option value="old" label='古い順'></option>
                {% endif %}
              </select>
              {% if request.GET.search %}
              <input name="search" value="{{ request.GET.search }}" type="hidden">
              {% endif %}
            </div>
            <div>
              <button type="submit">並べ替え</button>
            </div>
          </div>
          {% endif %}
        </form>
</div>
{% endblock edit %}

{% block object %}

{% block object__header %}
<div class="timeline"> 
{% endblock object__header %} 
    {% for object in object_list %}
    {% block object_content_and_icon %} 
    <div class="timeline__content">
        <div class="recipe-detail__icon">
            {% if object.user.icon  %}
            <img  class="profile__img" src="{{ object.user.icon.url }}">
            {% else %}
            <img class="profile__img" src="{% static 'img/illustration-2541681_1280.jpg' %}">
            {% endif %}
            <a href = "{% url 'eat:users' object.user.id %}">{{ object.user }}</a>
        </div>
        {% block object_content %}     
        {% if object.quote == "有り" %}
        <div class="timeline__inner yellow">
        {% else %}
        <div class="timeline__inner">
        {% endif %}
            <div class="title">
                <a href="{% url 'eat:detail' object.id %}">{{ object.recipe_name }}</a>
            </div>
            <div class="timeline-img">
                {% if object.photo %}
                    <img src="{{ object.photo.url }}">
                {% else %}
                    <img src="{% static 'img/smIMGL3647_TP_V.jpg' %}">
                {% endif %}            
            </div>
            <div class="objects">
                <div class="p">
                    <p>材料：{{ object.ingredient }}</p>
                    <p>種類：{{ object.type }}</p> 
                </div>
                <div class="count">
                    <div class="good">
                        {% if request.user in object.good_user.all %}
                        <p><a href="{% url 'eat:good' object.id %}"><span style="color:#FF0000">&hearts;</span></a>
                        {% else %}
                        <p><a href="{% url 'eat:good' object.id %}"><span style="color:#FF0000">&#9825;</span></a>
                        {% endif %}
                        {{ object.good_user.count }}
                    </div>
                    <div class="quote">
                        {% if  object.quote == "有り" %}
                        <!-- ログインユーザーと投稿者が同じ場合、Urlは表示しない-->
                        {% elif request.user == object.user %}
                        参考cook:{{ object.quote_user.count }}
                        {% else %}
                        <!-- 自分の投稿じゃない場合と投稿自体が参考cookじゃない場合、urlにアクセス可能　-->
                        <a href="{% url 'eat:quote_detail' object.id %}">参考cook:</a> {{ object.quote_user.count }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="time">
                {{ object.date | naturaltime  }}
            </div>
        </div>
        {% endblock object_content %}
        {% endblock object_content_and_icon %} 
</div>
{% endfor %}
{% endblock object %}

{% block pagination %}
<div class="pagination">
    <div class="pagination__content">
        <ul>
          {% if page_obj.has_previous %}
          <li class="active">
                <a class="button" href="?page={{ page_obj.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                </a>
          </li>
          {% endif %}
          
          {% for page in paginator.page_range %}
          <li {% if page == page_obj.number %} class="active" {% endif %}>
            {% if page == 1 %}
            <a class="button" href="?page={{ page }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}">
            {{ page }}
            </a>
            {% endif %}
          </li>
          {% endfor %}

        {% if page_obj.number >= 5 %}
        ...
        {% endif %}

          {% for page in paginator.page_range %}
          <li {% if page == page_obj.number %} class="active" {% endif %}>
                {% if  page_obj.number|add:"-4" < page and  page < page_obj.number|add:"4" and page != 1 and page != paginator.num_pages %}
                <a class="button" href="?page={{ page }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}">
                {{ page }}
                </a>
                {% endif %}
          </li>
          {% endfor %}
         
          {% if page_obj.number < paginator.num_pages|add:"-4" %}
          ...
          {% endif %}

          {% for page in paginator.page_range %}
          <li {% if page == page_obj.number %} class="active" {% endif %}>
            {% if page == paginator.num_pages %}
            <a class="button" href="?page={{ page }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}">
            {{ page }}
            </a>
            {% endif %}
          </li>
          {% endfor %}


          
    
          {% if page_obj.has_next %}
          <li class="active">
                <a class="button" href="?page={{ page_obj.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                </a>
          </li>
          {% endif %}
        </ul>
    </div>  
</div>
{% endblock pagination %}



{% endblock body %}

cook_css/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block body %}

<div class="form">
  <div class="form__content">
<form action = "" method = "post">
    {% csrf_token %}
  <table>

  {% for field in form %}
    <div class="form__label">
    {{ field.label }}
    {{ field }}
    </div>
  {% endfor %}


  {% for error in form.non_field_errors %}
    <div>
      <p>{{ error }}</p>
    </div>
  {% endfor %}




  </table>
  <div>
      <button type="submit">ログイン</button>
  </div>
  <div>
    <ul class="form__info">
    <li><span class="br">会員登録はお済みですか？</span>&rarr;<a href="{% url 'signup:new' %}">会員登録</a>へ進む</li>
    <li><span class="br">パスワードを忘れた場合</span>&rarr;<a href="{% url 'signup:password_reset' %}">パスワードの再設定</a></li>
    </ul>
  </div>
  </form>
</div>
</div>

{% endblock %}